In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [6]:
type(a)

numpy.ndarray

In [7]:
print(a+b)
print(a-b)
print(a*b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [8]:
# creating 2D array
a2 = np.array([[1,2], [3,4]])
print(a2)

[[1 2]
 [3 4]]


In [9]:
a3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [12]:
a4 = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(a4)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [11]:
# dimension shapes
print(a2.shape)
print(a2.ndim)
print(a2.dtype)

(2, 2)
2
int64


In [14]:
print(a2.shape)
print(a4.ndim)
print(a3.dtype)

(2, 2)
4
int64


In [15]:
np.arange(10)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
a = np.arange(11)
print(list(a))
print(type(a))

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]
<class 'numpy.ndarray'>


In [18]:
a = []
for i in range(1,21):
    a.append(i)
print(i)

20


In [19]:
np.random.randint(1,11, size=(2,3))

array([[ 1,  4,  9],
       [ 7, 10,  9]], dtype=int32)

In [21]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]])
y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [22]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [23]:
# matrix multiplication
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [24]:
# 2nd method
np.dot(x,y)

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [25]:
# multiplication of all elements of the array
x.prod()

np.int64(12600)

In [26]:
# mean
x.mean()

np.float64(3.3333333333333335)

In [27]:
y.mean()

np.float64(3.7777777777777777)

In [28]:
# row wise mean
x.mean(axis = 0)

array([4., 4., 2.])

In [ ]:
# row wise mean
y.mean(axis =1)

array([4.        , 4.        , 3.33333333])

In [30]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) # 1st quartile
print(np.percentile(a,50)) # median
print(np.percentile(a,75)) # 3rd quartile

3.0
5.0
7.0


In [34]:
b = np.random.randint(11,100, (4,4))
print(b)

[[83 65 85 74]
 [26 48 32 87]
 [38 61 96 49]
 [46 11 52 28]]


In [36]:
print('2X8')
print(b.reshape(2,8))


2X8
[[83 65 85 74 26 48 32 87]
 [38 61 96 49 46 11 52 28]]


In [38]:
print("8,2")
print(b.reshape(8,2))

8,2
[[83 65]
 [85 74]
 [26 48]
 [32 87]
 [38 61]
 [96 49]
 [46 11]
 [52 28]]


In [47]:
x = np.random.randint(1,11,(5,5))
print(x)

[[ 9  9  8  9  8]
 [ 4  8  1  9  6]
 [ 6  6  7  1  8]
 [ 5  2  1  1  2]
 [ 1  5  2  1 10]]


In [52]:
# indexing on array
print(x[0])
print(x[0,0])
print(x[-1])
print(x[1:])


[9 9 8 9 8]
9
[ 1  5  2  1 10]
[[ 4  8  1  9  6]
 [ 6  6  7  1  8]
 [ 5  2  1  1  2]
 [ 1  5  2  1 10]]


In [57]:

print(x[0:])
print(x[2:4])
print(x[3,4])
print(x[3:4])

[[ 9  9  8  9  8]
 [ 4  8  1  9  6]
 [ 6  6  7  1  8]
 [ 5  2  1  1  2]
 [ 1  5  2  1 10]]
[[6 6 7 1 8]
 [5 2 1 1 2]]
2
[[5 2 1 1 2]]
